name: cd
on: [ push ]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: docker build
      run: docker build --build-arg version=${{ github.sha }} --file Dockerfile --tag la3mmchen/alpine-build-stuff:latest .

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: print commit sha
      run: echo ${{ github.sha }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        name: la3mmchen/alpine-build-stuff
        tag: ${{ github.GITHUB_REF }}
        image: la3mmchen/alpine-build-stuff
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }} 
